### PR TITLE
Message Viewing Ordered

### PR DESCRIPTION
**Pull request by ikp-773**
Send messages were not ordered by anything the so the user have cant know which was send when and all.

I have sorted the send messages by date and time. So latest messages will be displayed first.

Also I have removed the debug banner.

### CODE REVIEW

**Comment by swaraj961** [comment]
> Send messages were not ordered by anything the so the user have cant know which was send when and all.
> 
> I have sorted the send messages by date and time. So latest messages will be displayed first.
> 
> Also I have removed the debug banner.

Great job @ikp-773  actually this is one of my old project,I'v been developing a similar kind of app soon it would be public. Also i'll look into your PR code in a while

**Comment by ikp-773** [comment]
> > Send messages were not ordered by anything the so the user have cant know which was send when and all.
> > I have sorted the send messages by date and time. So latest messages will be displayed first.
> > Also I have removed the debug banner.
> 
> Great job @ikp-773 actually this is one of my old project,I'v been developing a similar kind of app soon it would be public. Also i'll look into your PR code in a while

The really liked the colour theme of the app...Great Job.
Also is this repo invalid in hacktober fest?

**Comment by swaraj961** [comment]
> > > Send messages were not ordered by anything the so the user have cant know which was send when and all.
> > > I have sorted the send messages by date and time. So latest messages will be displayed first.
> > > Also I have removed the debug banner.
> > 
> > 
> > Great job @ikp-773 actually this is one of my old project,I'v been developing a similar kind of app soon it would be public. Also i'll look into your PR code in a while
> 
> The really liked the colour theme of the app...Great Job.
> Also is this repo invalid in hacktober fest?

Thanks for your words,
No it's not invalid, you can contribute to any repo for hacktober and they'll count your PR, i just added the label so that incase they review your PR they can find the tag here :)

**Comment by ikp-773** [comment]
Thanks a lot ;] @swaraj961

**Comment by ikp-773** [comment]
> > > > Send messages were not ordered by anything the so the user have cant know which was send when and all.
> > > > I have sorted the send messages by date and time. So latest messages will be displayed first.
> > > > Also I have removed the debug banner.
> > > 
> > > 
> > > Great job @ikp-773 actually this is one of my old project,I'v been developing a similar kind of app soon it would be public. Also i'll look into your PR code in a while
> > 
> > 
> > The really liked the colour theme of the app...Great Job.
> > Also is this repo invalid in hacktober fest?
> 
> Thanks for your words,
> No it's not invalid, you can contribute to any repo for hacktober and they'll count your PR, i just added the label so that incase they review your PR they can find the tag here :)

Thanks a lot ;)
Few more updates on the way ;)

**Comment by swaraj961** [comment]
Hey why do you close the PR ? @ikp-773 
I was busy this weekend

**Comment by ikp-773** [comment]
> Hey why do you close the PR ? @ikp-773
> I was busy this weekend

My bad...I thought I should close a PR after making all changes
Sorry😅

**Comment by ikp-773** [comment]
Btw my PR to the repo was marked ineligible...Do you know what caused it?

Screen Shot 2020-10-04 at 5 38 55 AM

**Comment by swaraj961** [comment]
> > Hey why do you close the PR ? @ikp-773
> > I was busy this weekend
> 
> My bad...I thought I should close a PR after making all changes
> Sorry😅

No you shouldn't close the PR unless it closed my maintainer or merged, when you fixed some issues or add some features to the repo .Now as its opened by me chances are this PR may not me counted in hacktober

**Comment by ikp-773** [comment]
> > > Hey why do you close the PR ? @ikp-773
> > > I was busy this weekend
> > 
> > 
> > My bad...I thought I should close a PR after making all changes
> > Sorry😅
> 
> No you shouldn't close the PR unless it closed my maintainer or mereged, when you fixed some issues or add some features to the repo .Now as its opened by me chances are this PR may not me counted in hacktober

No it was ineligible from the beginning. I have mailed them anyway so don't know what happened. Waiting for a reply.

**Comment by swaraj961** [comment]
@ikp-773  do one thing just close this PR and do a fresh one ig that should work.

> > > > Hey why do you close the PR ? @ikp-773
> > > > I was busy this weekend
> > > 
> > > 
> > > My bad...I thought I should close a PR after making all changes
> > > Sorry😅
> > 
> > 
> > No you shouldn't close the PR unless it closed my maintainer or mereged, when you fixed some issues or add some features to the repo .Now as its opened by me chances are this PR may not me counted in hacktober
> 
> No it was ineligible from the beginning. I have mailed them anyway so don't know what happened. Waiting for a reply.

Ohh that's weird, yup wait for reply

**Comment by ikp-773** [comment]
> @ikp-773 do one thing just close this PR and do a fresh one ig that should work.
> 
> > > > > Hey why do you close the PR ? @ikp-773
> > > > > I was busy this weekend
> > > > 
> > > > 
> > > > My bad...I thought I should close a PR after making all changes
> > > > Sorry😅
> > > 
> > > 
> > > No you shouldn't close the PR unless it closed my maintainer or mereged, when you fixed some issues or add some features to the repo .Now as its opened by me chances are this PR may not me counted in hacktober
> > 
> > 
> > No it was ineligible from the beginning. I have mailed them anyway so don't know what happened. Waiting for a reply.
> 
> Ohh that's weird, yup wait for reply

Something will happen soon...Untill then code ig😅

**Comment by swaraj961** [comment]
> > @ikp-773 do one thing just close this PR and do a fresh one ig that should work.
> > > > > > Hey why do you close the PR ? @ikp-773
> > > > > > I was busy this weekend
> > > > > 
> > > > > 
> > > > > My bad...I thought I should close a PR after making all changes
> > > > > Sorry😅
> > > > 
> > > > 
> > > > No you shouldn't close the PR unless it closed my maintainer or mereged, when you fixed some issues or add some features to the repo .Now as its opened by me chances are this PR may not me counted in hacktober
> > > 
> > > 
> > > No it was ineligible from the beginning. I have mailed them anyway so don't know what happened. Waiting for a reply.
> > 
> > 
> > Ohh that's weird, yup wait for reply
> 
> Something will happen soon...Untill then code ig😅

I'v been participating in hacktober since past 2-3 years nothing such happened with me but this year due to lot of spam PR's they may have done it they only actually check for PR , and merging is not mandatory . Just wait for them and you can easily close and create a new PR after their response.

**Comment by ikp-773** [comment]
> > > @ikp-773 do one thing just close this PR and do a fresh one ig that should work.
> > > > > > > Hey why do you close the PR ? @ikp-773
> > > > > > > I was busy this weekend
> > > > > > 
> > > > > > 
> > > > > > My bad...I thought I should close a PR after making all changes
> > > > > > Sorry😅
> > > > > 
> > > > > 
> > > > > No you shouldn't close the PR unless it closed my maintainer or mereged, when you fixed some issues or add some features to the repo .Now as its opened by me chances are this PR may not me counted in hacktober
> > > > 
> > > > 
> > > > No it was ineligible from the beginning. I have mailed them anyway so don't know what happened. Waiting for a reply.
> > > 
> > > 
> > > Ohh that's weird, yup wait for reply
> > 
> > 
> > Something will happen soon...Untill then code ig😅
> 
> I'v been participating in hacktober since past 2-3 years nothing such happened with me but this year due to lot of spam PR's they may have done it they only actually check for PR , and merging is not mandatory . Just wait for them and you can easily close and create a new PR after their response.

Will do that ;)

**Comment by ikp-773** [comment]
Hey there,
Hacktober fest 2020 rules changed.
It will only be accepted if u add hacktoberfest-accepted label.
Can you do that?

**Comment by swaraj961** [comment]
> Hey there,
> Hacktober fest 2020 rules changed.
> It will only be accepted if u add hacktoberfest-accepted label.
> Can you do that?

Done  thanks for your contribution 🎉

**Comment by ikp-773** [comment]
> > Hey there,
> > Hacktober fest 2020 rules changed.
> > It will only be accepted if u add hacktoberfest-accepted label.
> > Can you do that?
> 
> Done thanks for your contribution 🎉

Thank You.
Much Love ;)

**Pull request merged**
